added my stuff
eutampieri/OOP20-cs-DISIs-catacombs pull request #2
Opened 2021-05-06 11:46 UTC by MyK00L

2021-05-06 11:52 UTC, eutampieri requested changes
Interfaces should be prefixed with I, like IInterfaceName

2021-05-06 20:50 UTC, eutampieri commented on Chelli/ITileMap.cs
> +	int Width();
why not using a property?

2021-05-06 20:50 UTC, eutampieri commented on Chelli/ITileMap.cs
> +	Tile At(int x, int y);
There must be a IEnumerable way to do this

2021-05-06 20:50 UTC, eutampieri commented on Chelli/Tile.cs
> +	STAIRS,
I think they should be like `Void`, `Wall`, etc.

2021-05-06 20:50 UTC, eutampieri commented on Chelli/TileMapFactoryImpl.cs
> +				}
wow love u c#

2021-05-07 07:32 UTC, MyK00L commented on Chelli/TileMapFactoryImpl.cs
> +				}
ikr

2021-05-07 07:33 UTC, eutampieri approved these changes

2021-05-07 07:33 UTC, merged